import React, {Component} from 'react';
import {View, Text, ScrollView} from 'react-native';
import {globalStyles} from '../../style/globalStyles';
export default class PrivacyPolicy extends Component {
  render() {
    return (
      <View
        style={{
          flex: 1,
          paddingHorizontal: 6,
          backgroundColor: '#fff',
        }}>
        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{backgroundColor: '#fff', paddingTop: 20}}>
          <Text style={[globalStyles.normalTitle]}>Privacy Policy {'\n'}</Text>
          <Text style={[globalStyles.normalText]}>
            PRIVACY POLICY Welcome to Shopn! Shopn is owned and operated by
            Shopn LTD. Shopn values your privacy. This notice describes what
            information we collect, how we use it, and, if necessary, those with
            whom we share it. By using the Shopn services, you are accepting the
            practices described in this Privacy Policy. Your use of the services
            is also subject to our Terms and Conditions. This Privacy Policy may
            change from time to time. Your continued use of the services after
            we make changes is deemed to be acceptance of those changes, so
            please check the policy periodically for updates. This Privacy
            Policy has been developed and is maintained in accordance with all
            applicable federal and international laws and regulations and
            specifically with the Data Protection Act 2018 (UK regulation) and
            the GDPR (General Data Protection Regulation - European regulation).
            GENERAL INFORMATION The personal data of the users that are
            collected and processed through: • https://shopn.uk • Shopn Mobile
            App (Android and iOS version – Available on Google Play and App
            store) Will be under responsibility and in charge of: Shopn LTD
            (UK-registered company) 12876427 (contact@shopn.uk) (Hereinafter
            referred to as Shopn). TYPES OF INFORMATION GATHERED The information
            we learn from customers helps personalize and continually improve
            your experience at Shopn. Here are the types of information we
            gather: Information You Give Us. You provide information when you
            search, read and view the content, register as a user, buying a
            product or service, purchase the subscriptions as a seller, use the
            services and/or communicate with us. As a result of those actions,
            you might supply us with the following information: • First and last
            name • Email address • Phone number (includes WhatsApp number) •
            Address, State, Province, City • ZIP/Postal code • User content •
            Payment information • IP address • Any additional information
            relating to you that you provide to us directly through our
            services. Shopn will not collect any personally identifiable
            information about you, unless you provide it. Payment information:
            Your credit card information or payment information, will be
            processed by Apple Pay, Google Pay and PayPal (payment platforms
            available in Shopn) which will treat and safeguard your data with
            total security and with the exclusive purpose of processing the
            purchase of the subscriptions, products and services. Shopn reserves
            the right to contract any payment platform available in the market,
            which treats your data for the exclusive purpose of processing the
            purchase of the subscriptions, products and services. Please consult
            Apple Pay, Google Pay, PayPal privacy policy here:
            https://support.apple.com/en-us/HT203027
            https://policies.google.com/privacy
            https://www.paypal.com/us/webapps/mpp/ua/privacy-full GOOGLE
            Analytics. We use Google Analytics provided by Google, Inc., USA
            (“Google”). These tool and technologies collect and analyze certain
            types of information, including IP addresses, device and software
            identifiers, referring and exit URLs, feature use metrics and
            statistics, usage and purchase history, media access control address
            (MAC Address), mobile unique device identifiers, and other similar
            information via the use of cookies. The information generated by
            Google Analytics (including your IP address) may be transmitted to
            and stored by Google on servers in the United States. We use the
            GOOGLE Analytics collection of data to enhance the platform and
            improve our service. Please consult Google's privacy policy here:
            https://policies.google.com/privacy Facebook Pixel: Our platform
            uses Facebook pixels that enable us, our advertisers and service
            providers: • Collect statistics on our platforms and social networks
            (for example, number of users who visited a page). • Collect
            information about how you interact with our platforms and social
            networks (e.g., whether you opened or followed links contained
            within). • Personalize online services and marketing communications.
            • Match ads to users and optimize advertising campaigns. Please
            consult Facebook's privacy policy here:
            https://www.facebook.com/privacy/explanation Automatic Information.
            Like many platforms, we use "cookies." We obtain certain types of
            anonymous information which is not personally identifiable when your
            web browser accesses, Shopn or third-party content served by or on
            behalf of Shopn on other platforms. Some of the information we
            collect and analyze includes the Internet protocol (IP) address;
            computer and connection information such as browser type, version,
            and connection speed; purchase history; and the products you
            searched for, viewed, and possibly purchased. HOW LONG WE KEEP YOUR
            DATA Personal data will be kept for the time necessary for the
            provision of the services. The owner may be allowed to retain
            personal data for a longer period whenever the user has given
            consent to such processing, as long as such consent is not
            withdrawn. Furthermore, the owner may be obliged to retain personal
            data for a longer period whenever required to do so for the
            performance of a legal obligation or upon order of an authority.
            Once the retention period expires, personal data shall be deleted.
            Therefore, the right to access, the right to erasure, the right to
            rectification and the right to data portability cannot be enforced
            after expiration of the retention period. HOW WE USE YOUR
            INFORMATION. In general, we use the information we collect primarily
            to provide, maintain, protect and improve our current platform and
            services. We use personal information collected through our site as
            described below and described elsewhere in this Policy to: •
            Identify you as a user in our system. • User registration. • Publish
            users' products and services. • Facilitate communication between
            users. • Provide the subscriptions. • Process payments. • Improve
            our services, and how we operate our business. • Understand and
            enhance your experience using our services. • Respond to your
            comments or questions through our support team. • Send you related
            information, including confirmations, technical notices, updates,
            security alerts and support and administrative messages. •
            Communicate with you about upcoming events, offers and news about
            services offered by Shopn. • Marketing purposes of Shopn. • Protect,
            investigate and deter against fraudulent, unauthorized or illegal
            activity. HOW DO YOU GET MY CONSENT? By registering on the platform,
            purchasing subscriptions as a seller user, buy the products and
            services, posting content and providing us with personal information
            to communicate with you, you agree that we collect and use your
            information. You can withdraw your consent, contact us through the
            contact information or the contact page. SOCIAL NETWORKS On our
            platform and website you will find links and functions linked to
            different social networks, in which you can share your information.
            It is advisable to consult the privacy policy and data protection of
            each social network used on our platform. Facebook:
            https://www.facebook.com/privacy/explanation Instagram:
            http://instagram.com/about/legal/privacy/ Twitter:
            https://twitter.com/privacy HOW WE SHARE INFORMATION Information
            about our customers is an important part of our business, and we are
            not in the business of selling it to others. We share customer
            information only as described below. Other users: your data may be
            shared with other users for the sole purpose of publishing products
            and services. The shared data will be used and stored with the only
            purpose of publishing the products and services, according to this
            privacy policy. Third-Party Service Providers. We employ other
            companies and individuals to perform functions on our behalf.
            Examples include process payments (Apple Pay, Google Pay, PayPal),
            sending email, analyzing data, providing marketing assistance and
            providing search results and links. They have access to personal
            information needed to perform their functions, but may not use it
            for other purposes. Business Transfers. In the event that Shopn
            creates, merges with, or is acquired by another entity, your
            information will most likely be transferred. Shopn will email you or
            place a prominent notice on our Platform before your information
            becomes subject to another privacy policy. Protection of Shopn and
            others. We release personal information when we believe release is
            appropriate to comply with the law, enforce or apply our Terms and
            conditions and other agreements, or protect the rights, property, or
            safety of Shopn, our users or others. This includes exchanging
            information with other companies and organizations for fraud
            protection and credit risk reduction. With Your Consent. Other than
            as set out above, you will receive notice when personally
            identifiable information about you might go to third parties, and
            you will have an opportunity to choose not to share the information.
            Anonymous Information. Shopn uses the anonymous browsing information
            collected automatically by our servers primarily to help us
            administer and improve the services. We may also use aggregated
            anonymous information to provide information about the platform and
            services to potential business partners and other unaffiliated
            entities. This information is not personally identifiable. Email
            Address. The email address that you supply to us for purposes of
            receiving our email communications will never be rented or sold to a
            third party. PROTECTING YOUR INFORMATION We restrict authorized
            access to your personal information to those persons who have a
            legitimate purpose to know that information to provide products or
            services to you and those persons you have authorized to have access
            to such information. Shopn follows generally accepted industry
            standards to protect the personal information submitted to us, both
            during transmission and once Shopn receives it. No method of
            transmission over the Internet, or method of electronic storage, is
            100% secure. Therefore, while Shopn strives to use commercially
            acceptable means to protect your personal information, we cannot
            guarantee its absolute security. We will not sell, distribute, or
            lease your personal information to third parties unless we have your
            permission or are required by law to do so. YOUR RIGHTS You have the
            following rights in relation to your personal data provided to
            Shopn: • Access your personal data. • Request the correction of
            inaccurate data. • Request its deletion. • Request limitation of the
            processing of your data. • Oppose the treatment of your data. •
            Request your portability. • Not be subject to automated individual
            decisions. The Users can exercise all these rights contacting us
            through the contact information. EU MEMBERS’ RIGHTS (GDPR COMPLIANT)
            If you are habitually located in the European Union, you have the
            right to access, rectify, download or erase your information, as
            well as the right to restrict and object to certain processing of
            your information. While some of these rights apply generally,
            certain rights apply only in certain limited circumstances. We
            describe these rights below: • Access and Porting: You can access
            your information at any time. • Rectify, Restrict, Limit, Delete:
            You can also rectify, restrict, limit or delete much of your
            information by contact us. • Object: Where we process your
            information based on our legitimate interests explained above, or in
            the public interest, you can object to this processing in certain
            circumstances. In such cases, we will cease processing your
            information unless we have compelling legitimate grounds to continue
            processing or where it is needed for legal reasons. • Revoke
            consent: Where you have previously provided your consent, such as to
            permit us to process data about you, you have the right to withdraw
            your consent to the processing of your information at any time. For
            example, you can withdraw your consent by updating your settings. In
            certain cases, we may continue to process your information after you
            have withdrawn consent if we have a legal basis to do so or if your
            withdrawal of consent was limited to certain processing activities.
            • Complain: Should you wish to raise a concern about our use of your
            information (and without prejudice to any other rights you may
            have), you have the right to do so with your local supervisory
            authority. Additionally, if you are a European resident, we note
            that we are processing your information in order to fulfil contracts
            we might have with you or otherwise to pursue our legitimate
            business interests listed above. Additionally, please note that your
            information will be transferred outside of Europe. You can see more
            about these rights at:
            https://ec.europa.eu/info/law/law-topic/data-protection/reform/rights-citizens_en
            CHILDREN’S ONLINE PRIVACY PROTECTION We are in compliance with the
            requirements of the Data Protection Act 2018 (UK regulation) and the
            GDPR (General Data Protection Regulation - European regulation)
            regarding the protection of the personal data of minors. We do not
            collect any information from anyone under 13 years of age. Our
            platform and products are all directed to people who are at least 18
            years old or older. If you become aware that your child has provided
            us with personal information, please contact us. If we become aware
            that a child has provided us with personal information, we will take
            steps to delete that information, terminate that person's account,
            and restrict access to that person. EDITING AND DELETING INFORMATION
            If you believe that any information, we are holding on you is
            incorrect or incomplete, please write to or email us as soon as
            possible. We will promptly correct any information found to be
            incorrect. You can change, modify, rectify and delete your
            Information at any time, please contact us through the contact
            information. To opt-out of Shopn email, follow the instructions
            included in the email. Your request should be processed within 48
            hours. SUPPLIERS AND OTHER THIRD PARTIES Except as otherwise
            expressly included in this Privacy Policy, this document addresses
            only the use and disclosure of information Shopn collects from you.
            If you disclose your information to others, whether other users or
            suppliers on Shopn, different rules may apply to their use or
            disclosure of the information you disclose to them. Shopn does not
            control the privacy policies of third parties, and you are subject
            to the privacy policies of those third parties where applicable.
            Shopn is not responsible for the privacy or security practices of
            other platforms on the Internet, even those linked to or from the
            Shopn site. Shopn encourages you to ask questions before you
            disclose your personal information to others. CHANGES TO THIS
            PRIVACY POLICY Shopn will post modifications by date to this Privacy
            Policy to inform you of any changes. Shopn reserves the right to
            modify this Privacy Policy at any time, please review it frequently.
            CONTACT INFORMATION If you have questions or concerns about these
            Privacy Policy and the handling and security of your data, please
            contact us at: (contact@shopn.uk)
          </Text>
        </ScrollView>
      </View>
    );
  }
}
